version: "3.7"
services:  
  checkout:
    build:
      context: ../
      dockerfile: docker-environment/Dockerfiles/Dockerfile_igelCheckout
    networks:
      - hackathon
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
       KAFKA_BOOTSTRAPSERVERS: kafka:9092
  zookeeper:
    image: "confluentinc/cp-zookeeper:5.3.1"
    hostname: zookeeper
    networks:
      - hackathon
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: "confluentinc/cp-kafka:5.3.1"
    hostname: kafka
    networks:
      - hackathon
    ports:
      - 9093:9093
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  hackathon:
    driver: bridge
volumes:
  db-data:
    driver: local