spring.datasource:
  url: jdbc:postgresql://localhost:5432/demo
  username: demo
  password: demo
  driver-class-name: org.postgresql.Driver

spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  database:
    type: postgres
server.port: 8080
spring.devtools:
    restart:
      enabled: true
