spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - kafka:9092
      bindings:
        input:
          binder: kafka
          destination: serviceDrequest
          content-type: text/plain
          group: input-group-1
        output:
          binder: kafka
          destination: serviceDresponse
          group: output-group-1
          content-type: text/plain