version: '3.2'

services:
  elasticsearch:
    build:
        context: elk_config/elasticsearch
        args:
          ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: ./elk_config/elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PW}
    networks:
      - elk

  logstash:
    build:
        context: elk_config/logstash
        args:
          ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: ./elk_config/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./elk_config/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PW: ${ELASTIC_PW}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch
      - postgres

  kibana:
    build:
        context: elk_config/kibana
        args:
          ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: ./elk_config/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    environment:
      ELASTIC_PW: ${ELASTIC_PW}
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  postgres:
    image: postgres:11.2
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  dbdata:
