version: "3.7"
services:
  postgres:
    build:
      context: ..
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
      POSTGRES_DB: camunda
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
        - hackathon

  mountebank:
    build:
      context: ..
      dockerfile: ./docker/mountebank/Dockerfile
    ports:
      - "2525:2525"
      - "10000:10000"
    networks:
      - hackathon

  zeebe:
    image: camunda/zeebe:0.21.1
    hostname: zeebe
    networks:
      - hackathon
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - zeebe_data:/usr/local/zeebe/data
      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    depends_on:
      - elasticsearch

  operate:
    image: camunda/operate:1.1.0
    ports:
      - "8080:8080"
    volumes:
      - ./operate/application.yml:/usr/local/operate/config/application.yml
    networks:
      - hackathon
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - zeebe_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - hackathon

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.7.1
    ports:
      - "5601:5601"
    networks:
      - hackathon

  schaden-berechnen:
    build:
      context: ..
      dockerfile: ./docker/schaden-berechnen/Dockerfile
    networks:
      - hackathon
    depends_on:
      - zeebe
      - postgres
      - mountebank
      - kfz-regulieren
    ports:
      - 8081:8081

  kfz-regulieren:
    build:
      context: ..
      dockerfile: ./docker/kfz-regulieren/Dockerfile
    networks:
      - hackathon
    depends_on:
      - zeebe
    ports:
      - 8082:8082

  schaden-verbuchen:
    build:
      context: ..
      dockerfile: ./docker/schaden-verbuchen/Dockerfile
    networks:
      - hackathon
    depends_on:
      - zeebe
    ports:
      - 8083:8083

networks:
  hackathon:

volumes:
  db-data:
    driver: local
  zeebe_data:
  zeebe_elasticsearch_data: