FROM maven:3-jdk-8 as builder
VOLUME /tmp
WORKDIR /workspace

RUN mkdir -p igel-order/src
COPY igel-order/pom.xml ./igel-order
COPY igel-order/src ./igel-order/src

RUN mkdir -p igel-message-api/src
COPY igel-message-api/pom.xml ./igel-message-api
COPY igel-message-api/src ./igel-message-api/src

RUN cd igel-message-api && mvn install
RUN cd igel-order && mvn package

FROM openjdk:8-jre-alpine
COPY --from=builder /workspace/igel-order/target/igel-order-0.0.1-SNAPSHOT.jar /igel-order.jar
CMD ["java", "-jar", "/igel-order.jar"]