FROM maven:3-jdk-8 as builder
VOLUME /tmp
WORKDIR /workspace

RUN mkdir -p igel-payment/src
COPY igel-payment/pom.xml ./igel-payment
COPY igel-payment/src ./igel-payment/src

RUN mkdir -p igel-message-api/src
COPY igel-message-api/pom.xml ./igel-message-api
COPY igel-message-api/src ./igel-message-api/src

RUN cd igel-message-api && mvn install
RUN cd igel-payment && mvn package

FROM openjdk:8-jre-alpine
COPY --from=builder /workspace/igel-payment/target/igel-payment-0.0.1-SNAPSHOT.jar /igel-payment.jar
CMD ["java", "-jar", "/igel-payment.jar"]