FROM maven:3-jdk-8 as builder
VOLUME /tmp
WORKDIR /workspace

RUN mkdir -p igel-checkout/src
COPY igel-checkout/pom.xml ./igel-checkout
COPY igel-checkout/src ./igel-checkout/src

RUN mkdir -p igel-message-api/src
COPY igel-message-api/pom.xml ./igel-message-api
COPY igel-message-api/src ./igel-message-api/src

RUN cd igel-message-api && mvn install
RUN cd igel-checkout && mvn package

FROM openjdk:8-jre-alpine
COPY --from=builder /workspace/igel-checkout/target/igel-checkout-0.0.1-SNAPSHOT.jar /igel-checkout.jar
CMD ["java", "-jar", "/igel-checkout.jar"]