camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    filter:
      create: All tasks
    database:
      schema-update: true
      type: postgres
server:
  port : 8081
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/camunda
    username: camunda
    password: camunda
    driver-class-name: org.postgresql.Driver
schaden:
  customer:
    endpoint: "http://localhost:10000/customer"
zeebe:
  worker:
    name: "schaden-worker"
  client:
    broker:
      contactPoint: zeebe:26500
    security:
      plaintext: true